# Generated by Django 5.0.2 on 2024-03-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='css',
            field=models.BooleanField(default=0, verbose_name='CSS'),
        ),
        migrations.AddField(
            model_name='project',
            name='dj',
            field=models.BooleanField(default=0, verbose_name='DJango'),
        ),
        migrations.AddField(
            model_name='project',
            name='html',
            field=models.BooleanField(default=0, verbose_name='HTML'),
        ),
        migrations.AddField(
            model_name='project',
            name='jd',
            field=models.BooleanField(default=0, verbose_name='Javascript'),
        ),
        migrations.AddField(
            model_name='project',
            name='react',
            field=models.BooleanField(default=0, verbose_name='React'),
        ),
    ]
